Vet clinic database: add "join table" for visits
shm04/vet_clinic pull request #4
Opened 2023-08-05 20:25 UTC by shm04

## Add "join table" for visits.

### In this pull request I add the following changes:

- Create a table named vets with the following columns:
  - id: integer (set it as autoincremented PRIMARY KEY)
  - name: string
  - age: integer
  - date_of_graduation: date
- There is a many-to-many relationship between the tables species and vets: a vet can specialize in multiple species, and a species can have multiple vets specialized in it. Create a "join table" called specializations to handle this relationship.
- There is a many-to-many relationship between the tables animals and vets: an animal can visit multiple vets and one vet can be visited by multiple animals. Create a "join table" called visits to handle this relationship, it should also keep track of the date of the visit.
- Insert the following data for vets:
  - Vet William Tatcher is 45 years old and graduated Apr 23rd, 2000.
  - Vet Maisy Smith is 26 years old and graduated Jan 17th, 2019.
  - Vet Stephanie Mendez is 64 years old and graduated May 4th, 1981.
  - Vet Jack Harkness is 38 years old and graduated Jun 8th, 2008.
- Insert the following data for specializations:
  - Vet William Tatcher is specialized in Pokemon.
  - Vet Stephanie Mendez is specialized in Digimon and Pokemon.
  - Vet Jack Harkness is specialized in Digimon.
- Insert the following data for visits:
  - Agumon visited William Tatcher on May 24th, 2020.
  - Agumon visited Stephanie Mendez on Jul 22th, 2020.
  - Gabumon visited Jack Harkness on Feb 2nd, 2021.
  - Pikachu visited Maisy Smith on Jan 5th, 2020.
  - Pikachu visited Maisy Smith on Mar 8th, 2020.
  - Pikachu visited Maisy Smith on May 14th, 2020.
  - Devimon visited Stephanie Mendez on May 4th, 2021.
  - Charmander visited Jack Harkness on Feb 24th, 2021.
  - Plantmon visited Maisy Smith on Dec 21st, 2019.
  - Plantmon visited William Tatcher on Aug 10th, 2020.
  - Plantmon visited Maisy Smith on Apr 7th, 2021.
  - Squirtle visited Stephanie Mendez on Sep 29th, 2019.
  - Angemon visited Jack Harkness on Oct 3rd, 2020.
  - Angemon visited Jack Harkness on Nov 4th, 2020.
  - Boarmon visited Maisy Smith on Jan 24th, 2019.
  - Boarmon visited Maisy Smith on May 15th, 2019.
  - Boarmon visited Maisy Smith on Feb 27th, 2020.
  - Boarmon visited Maisy Smith on Aug 3rd, 2020.
  - Blossom visited Stephanie Mendez on May 24th, 2020.
  - Blossom visited William Tatcher on Jan 11th, 2021.
- Write queries to answer the following:
  - Who was the last animal seen by William Tatcher?
![image](https://github.com/shm04/vet_clinic/assets/99439509/78a6b654-8986-4e2e-a4a8-a58535234f03)
  - How many different animals did Stephanie Mendez see?
![image](https://github.com/shm04/vet_clinic/assets/99439509/10b9e5a3-9ffe-4cc2-a229-9eba57e96457)
  - List all vets and their specialties, including vets with no specialties.
![image](https://github.com/shm04/vet_clinic/assets/99439509/9389a967-05b8-4b97-93f0-9fcd47ff4a8e)
  - List all animals that visited Stephanie Mendez between April 1st and August 30th, 2020.
![image](https://github.com/shm04/vet_clinic/assets/99439509/b9e0ed9d-e8f5-4e22-a163-bf3569dfc87f)
  - What animal has the most visits to vets?
![image](https://github.com/shm04/vet_clinic/assets/99439509/f7b83f79-fafe-4dba-9a16-acb412826da1)
  - Who was Maisy Smith's first visit?
![image](https://github.com/shm04/vet_clinic/assets/99439509/bdfb2f5a-9cec-4d31-a0f7-55c39b162f4a)
  - Details for most recent visit: animal information, vet information, and date of visit.
![image](https://github.com/shm04/vet_clinic/assets/99439509/b3824a9a-168c-43dd-98ec-90de886a83c5)
  - How many visits were with a vet that did not specialize in that animal's species?
![image](https://github.com/shm04/vet_clinic/assets/99439509/bda3acfb-6077-4d3f-9815-940eecb62fcd)
  - What specialty should Maisy Smith consider getting? Look for the species she gets the most.
![image](https://github.com/shm04/vet_clinic/assets/99439509/19fc525b-a12b-4b95-83df-8e379ce0d305)

2023-08-05 23:09 UTC, Munsa1 requested changes
Hi @shm04, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
Provided Screenshots For Every Query :heavy_check_mark: 
Correct Git Flow :heavy_check_mark: 
Descriptive ReadMe File :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
n/a

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-05 23:09 UTC, Munsa1 commented on queries.sql
> +SELECT COUNT(*) AS num_visits_not_specialized FROM visits JOIN animals ON visits.animal_id = animals.id JOIN vets ON visits.vet_id = vets.id LEFT JOIN specializations ON vets.id = specializations.vet
- [ ] Here we can see that `Maisy Smith` has no specialty hence every animal that visited her should be counted, and those animals are 9 in total, this excluding the other animals that have a specialty but saw animals they were not specialized in, So we can see that the query output is incorrect. kindly fix this.

Given data
![image](https://github.com/shm04/vet_clinic/assets/81932478/72c5103c-df31-478f-84d9-68bfa3434d7b)

Your output
![image](https://github.com/shm04/vet_clinic/assets/81932478/c6dc80f9-7f78-4801-b51e-5054c3734dd6)

2023-08-05 23:09 UTC, Munsa1 commented on queries.sql
> +SELECT vets.name, species.name FROM vets LEFT JOIN specializations ON vets.id = specializations.vet_id LEFT JOIN species ON specializations.species_id = species.id ORDER BY vets.id, species.id;
- [ ] Kindly list the correct values for the vets and their specialties.

List all vets and their specialties, including vets with no specialties.
Answer:

William Tatcher (Specialty: Pokemon)
Maisy Smith (No Specialties)
Stephanie Mendez (Specialties: Pokemon, Digimon)
Jack Harkness (Specialty: Digimon)

2023-08-05 23:41 UTC, shm04 commented on queries.sql
> +SELECT animals.name FROM animals JOIN visits ON visits.animal_id = animals.id WHERE visits.visit_date BETWEEN '2020-04-01' AND '2020-08-30';
In this, I think the correct answer is Agumon and Blossom, Pikachu didn't go with Stephanie and Plantom neither

2023-08-05 23:43 UTC, shm04 commented on queries.sql
> +ORDER BY visits.visit_date DESC LIMIT 1;
This also correct because Blossom went on January and Devimon on May

2023-08-06 00:17 UTC, Munsa1 approved these changes
Hi @shm04, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
Made Requested Changes :heavy_check_mark: 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-06 00:20 UTC, merged